name: Test

on:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pytest-ruff-version:
          - "0.2.1"
          - "0.3"
          - "0.3.1"
          - "0.3.2"
          - "0.4.0"
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install ruff
        run: pip install "pytest-ruff==${{ matrix.pytest-ruff-version }}"

      - name: Install test package
        run: pip install .

      - name: Run Hello
        run: ruff-hello

      - name: print ruff versions
        run: pip list|grep ruff

      - name: Run pytest
        run: pytest -v

